name: clean_architecture_module
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
# Service locator / dependency_injection
  provider:
  get_it:
# Remote API
  dio:
  internet_connection_checker:
  connectivity_plus:
# State management
  bloc:
  flutter_bloc:
  get:
  redux:
# Local cache
  flutter_secure_storage:
  shared_preferences:
# Local DB
  hive:
  drift:
# Value equality
  equatable:
# Defines the annotations
  freezed_annotation:
  json_annotation:
# Navigation
  auto_route:
# Functional programming thingies
  dartz:
# Svg images
  flutter_svg:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
# Standalone generator and watcher
  build_runner:
# Builders for handling
  freezed:
  json_serializable:
# A generator for [auto_route] library.
  auto_route_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/

